services:
  movie-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - proxy-network
    ports:
      - 3000:3000

  nginx:
    image: nginx:stable-perl
    container_name: nginx-grumly-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-grumly.conf:/etc/nginx/conf.d/default.conf
      - nginx-logs:/var/log/nginx
      # SSL certificates (uncomment and adjust paths as needed)
      - ./ssl/nginx-selfsigned.crt:/etc/nginx/ssl/cert.crt:ro
      - ./ssl/nginx-selfsigned.key:/etc/nginx/ssl/private.key:ro
    networks:
      - proxy-network
      - default
    restart: unless-stopped
    depends_on:
      - movie-app

    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  nginx-logs:
    driver: local

networks:
  proxy-network:
    name: grumly-proxy-network
    driver: bridge
    external: false
